//! Feature coverage of the generated end-to-end YAML benchmark suite (#327).
//!
//! The suite under `data/bench/generated/yaml` is what exercises the **query
//! and streaming** paths (`dev bench yq`, `benches/yq_comparison.rs`,
//! `benches/yq_select.rs`); `benches/yaml_bench.rs` covers index **build** over
//! its own fixtures. When a construct is absent from the generated suite,
//! "every end-to-end benchmark is neutral" carries no information about it —
//! the blind spot that let the quadratic sequence-iteration bug of #106 survive
//! a full benchmark run.
//!
//! So this test asserts, on every CI leg:
//!
//! 1. every construct `src/yaml/mod.rs` lists as **supported** is generated by
//!    at least one pattern;
//! 2. every construct listed as **out of scope** is generated by **none** —
//!    each with a reason, so fixing one flips this test instead of silently
//!    widening what the benchmarks measure;
//! 3. each feature-focused pattern still carries its own headline feature;
//! 4. the `yaml generate --pattern` value list and the `yaml generate-suite`
//!    output agree, so a pattern cannot be registered in one and missed in the
//!    other.
//!
//! Features are read from the **index** — `YamlCursor::style()`,
//! `YamlIndex::get_anchor_name`, `YamlIndex::is_alias`, the root document
//! count — the same way `src/bin/succinctly/corpus_stats.rs` derives its corpus
//! shape metrics, so this measures what the parser actually saw rather than
//! what a regex thinks the bytes say.
//!
//! Hermetic: generates through the CLI, needs no `yq` and no committed data
//! (`data/bench/generated/` is gitignored).
//!
//! Run with: cargo test --features cli --test yaml_bench_suite_coverage

#![cfg(feature = "cli")]

use std::collections::BTreeSet;
use std::process::Command;

use succinctly::yaml::{YamlCursor, YamlIndex, YamlValue};

/// Size generated per pattern. Large enough for every generator to reach the
/// less frequent branches of its size mix, small enough to stay fast.
const PROBE_SIZE: &str = "64kb";

/// A YAML construct the suite is checked for.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
enum Feature {
    FlowMapping,
    FlowSequence,
    Anchor,
    Alias,
    LiteralBlockScalar,
    FoldedBlockScalar,
    ExplicitKey,
    MultiDocument,
    MergeKey,
    Tag,
}

impl Feature {
    fn name(self) -> &'static str {
        match self {
            Self::FlowMapping => "flow mapping `{...}`",
            Self::FlowSequence => "flow sequence `[...]`",
            Self::Anchor => "anchor `&name`",
            Self::Alias => "alias `*name`",
            Self::LiteralBlockScalar => "literal block scalar `|`",
            Self::FoldedBlockScalar => "folded block scalar `>`",
            Self::ExplicitKey => "explicit key `? `",
            Self::MultiDocument => "multi-document `---`",
            Self::MergeKey => "merge key `<<:`",
            Self::Tag => "tag `!!str`",
        }
    }
}

/// Constructs `src/yaml/mod.rs` lists as supported. Each must appear in at
/// least one generated pattern.
const REQUIRED: &[Feature] = &[
    Feature::FlowMapping,
    Feature::FlowSequence,
    Feature::Anchor,
    Feature::Alias,
    Feature::LiteralBlockScalar,
    Feature::FoldedBlockScalar,
    Feature::ExplicitKey,
    Feature::MultiDocument,
];

/// Constructs deliberately kept out of the suite, with the reason. Generating
/// any of these would make the affected files diverge from `yq`, so a
/// benchmark comparison over them would measure two different computations.
///
/// When one is fixed, delete its row here and give it a pattern: this test
/// turns the fix into a required edit rather than leaving the coverage gap in
/// place.
const OUT_OF_SCOPE: &[(Feature, &str)] = &[
    (
        Feature::MergeKey,
        "parsed as an ordinary key, so output is {\"<<\": {...}} where yq splices (#171)",
    ),
    (
        Feature::Tag,
        "rejected outright in block context (documented non-support in src/yaml/mod.rs)",
    ),
];

/// The feature each pattern added by #327 exists to carry.
const HEADLINE: &[(&str, &[Feature])] = &[
    ("flow", &[Feature::FlowMapping, Feature::FlowSequence]),
    ("anchors", &[Feature::Anchor, Feature::Alias]),
    (
        "block-scalars",
        &[Feature::LiteralBlockScalar, Feature::FoldedBlockScalar],
    ),
    ("explicit-keys", &[Feature::ExplicitKey]),
    ("multi-doc", &[Feature::MultiDocument]),
];

// ---------------------------------------------------------------------------
// Generation
// ---------------------------------------------------------------------------

/// Pattern names accepted by `yaml generate --pattern`, read from clap's help
/// so the list cannot drift from the CLI enum.
fn cli_pattern_names() -> Vec<String> {
    let output = Command::new(env!("CARGO_BIN_EXE_succinctly"))
        .args(["yaml", "generate", "--help"])
        .output()
        .expect("failed to run `yaml generate --help`");
    assert!(output.status.success(), "`yaml generate --help` failed");

    let help = String::from_utf8_lossy(&output.stdout);

    // Long help renders the value list as `- <name>: <description>` under a
    // "Possible values:" heading.
    let names: Vec<String> = help
        .lines()
        .skip_while(|line| !line.trim_start().starts_with("Possible values:"))
        .skip(1)
        .map_while(|line| line.trim_start().strip_prefix("- ").map(str::to_string))
        .filter_map(|entry| {
            entry
                .split_once(':')
                .map(|(name, _)| name.trim().to_string())
        })
        .collect();

    assert!(
        !names.is_empty(),
        "could not read the pattern list from `yaml generate --help`:\n{help}"
    );
    names
}

fn generate(pattern: &str) -> Vec<u8> {
    let output = Command::new(env!("CARGO_BIN_EXE_succinctly"))
        .args(["yaml", "generate", PROBE_SIZE, "--pattern", pattern])
        .arg("--seed")
        .arg("42")
        .output()
        .unwrap_or_else(|e| panic!("failed to generate pattern {pattern}: {e}"));
    assert!(
        output.status.success(),
        "`yaml generate --pattern {pattern}` failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    output.stdout
}

// ---------------------------------------------------------------------------
// Index-derived feature detection
// ---------------------------------------------------------------------------

fn walk(cur: YamlCursor<'_, Vec<u64>>, found: &mut BTreeSet<Feature>) {
    let flow = cur.style() == "flow";

    match cur.value() {
        YamlValue::String(_) => match cur.style() {
            "literal" => {
                found.insert(Feature::LiteralBlockScalar);
            }
            "folded" => {
                found.insert(Feature::FoldedBlockScalar);
            }
            _ => {}
        },
        YamlValue::Mapping(fields) => {
            if flow {
                found.insert(Feature::FlowMapping);
            }
            for field in fields {
                if let YamlValue::String(key) = field.key() {
                    if key.raw_bytes() == b"<<" {
                        found.insert(Feature::MergeKey);
                    }
                }
                walk(field.value_cursor(), found);
            }
        }
        YamlValue::Sequence(elements) => {
            if flow {
                found.insert(Feature::FlowSequence);
            }
            let mut rest = elements;
            while let Some((child, tail)) = rest.uncons_cursor() {
                walk(child, found);
                rest = tail;
            }
        }
        // Aliases are counted from the BP scan; do not recurse (cycle-safe).
        YamlValue::Alias { .. } | YamlValue::Null | YamlValue::Error(_) => {}
    }
}

/// Features present in one generated document, read from its index.
fn features_of(pattern: &str, bytes: &[u8]) -> BTreeSet<Feature> {
    let index = YamlIndex::build(bytes)
        .unwrap_or_else(|e| panic!("generated {pattern} does not parse: {e:?}"));
    let mut found = BTreeSet::new();

    // Anchors and aliases have no bulk accessor; scan the BP opens as
    // corpus_stats.rs does.
    let bp = index.bp();
    for p in 0..bp.len() {
        if !bp.is_open(p) {
            continue;
        }
        if index.get_anchor_name(p).is_some() {
            found.insert(Feature::Anchor);
        }
        if index.is_alias(p) {
            found.insert(Feature::Alias);
        }
    }

    // The root is a virtual sequence of documents: more than one child means a
    // multi-document stream.
    let root = index.root(bytes);
    match root.value() {
        YamlValue::Sequence(mut docs) => {
            let mut count = 0;
            while let Some((doc, rest)) = docs.uncons_cursor() {
                count += 1;
                walk(doc, &mut found);
                docs = rest;
            }
            if count > 1 {
                found.insert(Feature::MultiDocument);
            }
        }
        _ => walk(root, &mut found),
    }

    // Two constructs the index does not distinguish: an explicit key is an
    // ordinary key once indexed, and a tag would have failed the build above.
    let text = String::from_utf8_lossy(bytes);
    if text.starts_with("? ") || text.contains("\n? ") {
        found.insert(Feature::ExplicitKey);
    }
    if text.contains("!!") {
        found.insert(Feature::Tag);
    }

    found
}

/// Every pattern's features, keyed by pattern name.
fn suite_features() -> Vec<(String, BTreeSet<Feature>)> {
    cli_pattern_names()
        .into_iter()
        .map(|pattern| {
            let bytes = generate(&pattern);
            let features = features_of(&pattern, &bytes);
            (pattern, features)
        })
        .collect()
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

/// The out-of-scope assertions are negative — they pass when nothing is found,
/// which is also what a broken detector does. This pins that each one actually
/// fires on input containing the construct.
#[test]
fn detector_finds_every_feature_it_claims_to() {
    let cases: &[(Feature, &str)] = &[
        (Feature::FlowMapping, "a: {k: v}\n"),
        (Feature::FlowSequence, "a: [1, 2]\n"),
        (Feature::Anchor, "a: &anc\n  k: v\n"),
        (Feature::Alias, "a: &anc\n  k: v\nb: *anc\n"),
        (Feature::LiteralBlockScalar, "a: |\n  text\n"),
        (Feature::FoldedBlockScalar, "a: >\n  text\n"),
        (Feature::ExplicitKey, "? key\n: value\n"),
        (Feature::MultiDocument, "---\na: 1\n---\nb: 2\n"),
        (Feature::MergeKey, "base: &b\n  a: 1\nc:\n  <<: *b\n"),
    ];

    for (feature, yaml) in cases {
        let found = features_of("self-test", yaml.as_bytes());
        assert!(
            found.contains(feature),
            "detector missed {} in:\n{yaml}",
            feature.name()
        );
    }

    // Tags never reach the index — the parser rejects them — so the tag check
    // is text-based and is pinned separately.
    assert!(
        YamlIndex::build(b"a: !!str 1\n").is_err(),
        "tags now parse; the Tag detection here needs to move to the index"
    );
}

#[test]
fn every_supported_feature_is_generated() {
    let suite = suite_features();

    let missing: Vec<&str> = REQUIRED
        .iter()
        .filter(|f| !suite.iter().any(|(_, found)| found.contains(f)))
        .map(|f| f.name())
        .collect();

    assert!(
        missing.is_empty(),
        "no generated pattern produces: {}\n\
         The end-to-end suite cannot measure a change to these constructs, so a \
         neutral benchmark result over them means nothing. Add them to a pattern \
         in src/bin/succinctly/yaml_generators.rs, or record them in OUT_OF_SCOPE \
         with a reason.",
        missing.join(", ")
    );
}

#[test]
fn out_of_scope_features_are_not_generated() {
    let suite = suite_features();

    for (feature, reason) in OUT_OF_SCOPE {
        let offenders: Vec<&str> = suite
            .iter()
            .filter(|(_, found)| found.contains(feature))
            .map(|(pattern, _)| pattern.as_str())
            .collect();

        assert!(
            offenders.is_empty(),
            "pattern(s) {} generate {}, which is out of scope: {reason}\n\
             If the underlying divergence is fixed, move this feature into \
             REQUIRED and give it a pattern.",
            offenders.join(", "),
            feature.name()
        );
    }
}

#[test]
fn feature_patterns_carry_their_headline_feature() {
    let suite = suite_features();

    for (pattern, expected) in HEADLINE {
        let found = suite
            .iter()
            .find(|(name, _)| name == pattern)
            .unwrap_or_else(|| panic!("pattern {pattern} is not registered with the CLI"));

        for feature in *expected {
            assert!(
                found.1.contains(feature),
                "pattern {pattern} no longer generates {} — the pattern exists to \
                 carry that construct end-to-end",
                feature.name()
            );
        }
    }
}

#[test]
fn generate_suite_covers_every_cli_pattern() {
    let dir =
        std::env::temp_dir().join(format!("succinctly-suite-coverage-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);

    let output = Command::new(env!("CARGO_BIN_EXE_succinctly"))
        .args(["yaml", "generate-suite", "--output-dir"])
        .arg(&dir)
        .args(["--max-size", "1kb", "--clean", "--verify"])
        .output()
        .expect("failed to run `yaml generate-suite`");
    assert!(
        output.status.success(),
        "`yaml generate-suite` failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );

    let generated: BTreeSet<String> = std::fs::read_dir(&dir)
        .expect("suite directory missing")
        .map(|e| {
            e.expect("unreadable entry")
                .file_name()
                .to_string_lossy()
                .into_owned()
        })
        .collect();

    let missing: Vec<String> = cli_pattern_names()
        .into_iter()
        .filter(|p| !generated.contains(p))
        .collect();

    let _ = std::fs::remove_dir_all(&dir);

    assert!(
        missing.is_empty(),
        "pattern(s) {} are accepted by `yaml generate` but produce no directory in \
         `yaml generate-suite` — register them in yaml_generators::ALL_PATTERNS",
        missing.join(", ")
    );
}
