#!/usr/bin/env bash
#
# Capture the pinned jq's error messages for the probes in
# tests/data/jq-error-probes.tsv.
#
# The captured messages drive tests/jq_error_message_tests.rs, which asserts
# that both succinctly evaluators word their errors exactly as jq does (#356).
# As with the goldens, the oracle is jqlang/jq at the version pinned in
# tests/data/jq-golden/JQ_VERSION — never succinctly's own output, which would
# enshrine succinctly's wording as "correct".
#
# Usage:
#   ./scripts/sync-jq-error-messages.sh           # regenerate the message table
#   ./scripts/sync-jq-error-messages.sh --check   # verify it matches pinned jq
#
# Every probe must make jq error. A probe that produces output instead is a
# hard failure: this corpus describes error wording only, so a silent success
# means either a bad probe or a jq behaviour change that needs a human look.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROBES="$REPO_ROOT/tests/data/jq-error-probes.tsv"
TABLE="$REPO_ROOT/tests/data/jq-error-messages.tsv"
PIN="$(cat "$REPO_ROOT/tests/data/jq-golden/JQ_VERSION")"

check_only=false
[[ "${1:-}" == "--check" ]] && check_only=true

command -v jq >/dev/null 2>&1 || {
  echo "error: jq not found on PATH — install jqlang/jq $PIN" >&2
  echo "  https://github.com/jqlang/jq/releases/tag/$PIN" >&2
  exit 1
}

# Same pin rule as scripts/sync-jq-golden.sh: accept the pinned token exactly
# or with a platform suffix ("$PIN-apple" on the macOS system build), so one
# table verifies on both the CI Linux runner and a developer's macOS.
version_line="$(jq --version)"
if [[ "$version_line" != "$PIN" && "$version_line" != "$PIN-"* ]]; then
  echo "error: jq on PATH is '$version_line' but probes are pinned to $PIN" >&2
  echo "  install $PIN from https://github.com/jqlang/jq/releases/tag/$PIN" >&2
  exit 1
fi

work_dir="$(mktemp -d)"
trap 'rm -rf "$work_dir"' EXIT
out="$work_dir/table.tsv"

{
  echo "# GENERATED by ./scripts/sync-jq-error-messages.sh from jq $PIN —"
  echo "# do not hand-edit. Columns: <id>	<filter>	<input-json>	<jq message>"
  echo "# Probes live in tests/data/jq-error-probes.tsv; the consumer is"
  echo "# tests/jq_error_message_tests.rs."
} > "$out"

count=0
seen_ids="$work_dir/ids"
: > "$seen_ids"

while IFS=$'\t' read -r id filter input rest || [[ -n "${id:-}" ]]; do
  # Skip comments and blank lines.
  [[ -z "$id" || "$id" == \#* ]] && continue

  [[ -n "$filter" && -n "$input" ]] || {
    echo "error: probe '$id' must have all three tab-separated columns" >&2
    exit 1
  }
  [[ -z "$rest" ]] || {
    echo "error: probe '$id' has a 4th column — did a filter contain a tab?" >&2
    exit 1
  }
  if grep -qxF "$id" "$seen_ids"; then
    echo "error: duplicate probe id '$id'" >&2
    exit 1
  fi
  echo "$id" >> "$seen_ids"

  # jq exits 5 on a runtime error, so `set -e` must not see the failure. A
  # probe that SUCCEEDS is the error case we care about here.
  if printf '%s' "$input" | jq -c "$filter" > "$work_dir/stdout" 2> "$work_dir/stderr"; then
    echo "error: probe '$id' did not make jq error — it printed:" >&2
    sed 's/^/    /' < "$work_dir/stdout" >&2
    echo "  remove it from tests/data/jq-error-probes.tsv, or fix the probe" >&2
    exit 1
  fi

  # jq prefixes runtime errors with "jq: error (at <stdin>:N): "; the location
  # is not part of the message succinctly raises, so strip it. Compile errors
  # ("jq: error: … is not defined") mean the probe is not a runtime error at
  # all, so reject them rather than record a message no evaluator can produce.
  message="$(sed -e 's/^jq: error (at [^)]*): //' "$work_dir/stderr" | head -1)"
  if [[ "$message" == jq:\ error* || -z "$message" ]]; then
    echo "error: probe '$id' produced a non-runtime jq error:" >&2
    sed 's/^/    /' < "$work_dir/stderr" >&2
    exit 1
  fi

  printf '%s\t%s\t%s\t%s\n' "$id" "$filter" "$input" "$message" >> "$out"
  count=$((count + 1))
done < "$PROBES"

[[ $count -gt 0 ]] || { echo "error: no probes found in $PROBES" >&2; exit 1; }

if $check_only; then
  if ! diff -u "$TABLE" "$out"; then
    echo "error: $TABLE is out of date — run ./scripts/sync-jq-error-messages.sh" >&2
    exit 1
  fi
  echo "$count jq error messages up to date with jq $PIN" >&2
else
  cp "$out" "$TABLE"
  echo "captured $count error messages from jq $PIN into ${TABLE#"$REPO_ROOT/"}" >&2
fi
