#!/usr/bin/env bash
#
# Capture the pinned jq's complete builtin roster into
# tests/data/jq-builtin-names.txt.
#
# The roster is what `src/jq/resolve.rs`'s compile-time resolution pass treats
# as "a name real jq defines" (#1473). succinctly lowers the builtins it
# implements to typed `Builtin::*` variants at parse time, so those never reach
# the resolver at all — the roster matters only for the ~45 jq builtins
# succinctly does *not* implement (the libm family, `JOIN`, `format/1`,
# `input_filename`, ...), which do reach it as bare `Expr::FuncCall`s. Without
# the roster the resolver would reject `if false then cbrt else 1 end` at
# compile time, where real jq compiles it happily.
#
# As with the goldens, the oracle is jqlang/jq at the version pinned in
# tests/data/jq-golden/JQ_VERSION — never succinctly's own `builtins` output,
# which would enshrine succinctly's own coverage as "what jq defines".
#
# Usage:
#   ./scripts/sync-jq-builtin-names.sh           # regenerate the roster
#   ./scripts/sync-jq-builtin-names.sh --check   # verify it matches pinned jq
#
# The const table in src/jq/resolve.rs is checked against this file by
# `test_jq_builtin_roster_matches_pinned_oracle` in tests/jq_cli_tests.rs, so
# regenerating here without updating the table is a test failure, not a silent
# drift.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ROSTER="$REPO_ROOT/tests/data/jq-builtin-names.txt"
PIN="$(cat "$REPO_ROOT/tests/data/jq-golden/JQ_VERSION")"

check_only=false
[[ "${1:-}" == "--check" ]] && check_only=true

command -v jq >/dev/null 2>&1 || {
  echo "error: jq not found on PATH — install jqlang/jq $PIN" >&2
  echo "  https://github.com/jqlang/jq/releases/tag/$PIN" >&2
  exit 1
}

# Same pin rule as scripts/sync-jq-error-messages.sh: accept the pinned token
# exactly or with a platform suffix ("$PIN-apple" on the macOS system build),
# so one roster verifies on both the CI Linux runner and a developer's macOS.
version_line="$(jq --version)"
if [[ "$version_line" != "$PIN" && "$version_line" != "$PIN-"* ]]; then
  echo "error: jq on PATH is '$version_line' but the roster is pinned to $PIN" >&2
  echo "  install $PIN from https://github.com/jqlang/jq/releases/tag/$PIN" >&2
  exit 1
fi

work_dir="$(mktemp -d)"
trap 'rm -rf "$work_dir"' EXIT
out="$work_dir/roster.txt"

{
  echo "# GENERATED by ./scripts/sync-jq-builtin-names.sh from jq $PIN —"
  echo "# do not hand-edit. One <name>/<arity> per line, sorted."
  echo "# Consumed by src/jq/resolve.rs's JQ_BUILTIN_ROSTER const, which"
  echo "# tests/jq_cli_tests.rs checks against this file."
  jq -rn 'builtins | .[]' | LC_ALL=C sort
} > "$out"

if $check_only; then
  if diff -u "$ROSTER" "$out"; then
    echo "roster up to date with jq $PIN ($(grep -cv '^#' "$ROSTER") builtins)"
  else
    echo "error: roster is stale — run ./scripts/sync-jq-builtin-names.sh" >&2
    exit 1
  fi
else
  mv "$out" "$ROSTER"
  echo "wrote $ROSTER ($(grep -cv '^#' "$ROSTER") builtins from jq $PIN)"
fi
